/**
 * The transport, exercised entirely in process.
 *
 * Every network fact asserted here comes from `test/fixtures/rest/responses.json` — real captured
 * responses, including all four observed error shapes and the `{"seconds":1805}` body that carries
 * no `code` field at all. Where a shape was *not* captured (the HTTP 401 auth refusal, and the
 * CloudFront HTML interstitial) the case is synthesised from `spec/05-rest-api.md` §1.2 / §4.2 and
 * says so inline, because a synthesised fixture is weaker evidence and the difference should be
 * visible to whoever reads a failure.
 *
 * The credential used throughout is the real token from `conformance/vectors/tx.json` →
 * `authTokens[0].token`, so the percent-encoding, the redaction regexes and the header shape are
 * all exercised against a genuine one.
 */

import { readFileSync } from "node:fs";

import { describe, expect, test } from "bun:test";

import type { AuthProvider, Diagnostic } from "../../src/config/config.js";
import {
  LighterApiError,
  LighterAuthError,
  LighterBlockedError,
  LighterConfigError,
  LighterTimeoutError,
  LighterTransportError,
  LighterValidationError,
  isLighterApiError,
  isLighterAuthError,
} from "../../src/errors.js";
import type { OrderBooks } from "../../src/models/market.js";
import type { RespWithdrawalDelay } from "../../src/models/misc.js";
import type { RespSendTx } from "../../src/models/transaction.js";
import type { RouteDef } from "../../src/rest/route-types.js";
import { routes } from "../../src/rest/routes.js";
import {
  LighterGeoRestrictedError,
  buildQuery,
  buildUrl,
  classifyResponse,
  isLighterGeoRestrictedError,
  isRetryableStatus,
  isSuccess,
  parseRetryAfterMs,
  request,
  retryDelayMs,
  stripTrailingSlash,
} from "../../src/rest/transport.js";

/** Minimal ambient for the import-purity subprocess check. */
declare const Bun: {
  spawnSync(cmd: string[], opts?: { stdout?: "pipe"; stderr?: "pipe" }): {
    exitCode: number;
    stdout: { toString(): string };
    stderr: { toString(): string };
  };
};

/* ---------------------------------------------------------------------------------------------- */
/* Evidence                                                                                         */
/* ---------------------------------------------------------------------------------------------- */

interface FixtureCase {
  readonly request: { readonly path: string };
  readonly status: number;
  readonly contentType: string;
  readonly bodyIsJson: boolean;
  readonly apiCode: number | null;
  readonly body: unknown;
}

const fixtures = JSON.parse(
  readFileSync(new URL("../fixtures/rest/responses.json", import.meta.url), "utf8"),
) as { readonly cases: Record<string, FixtureCase> };

function fixture(name: string): FixtureCase {
  const found: FixtureCase | undefined = fixtures.cases[name];
  if (found === undefined) throw new Error(`no fixture named ${name}`);
  return found;
}

const vectors = JSON.parse(
  readFileSync(new URL("../../conformance/vectors/tx.json", import.meta.url), "utf8"),
) as { readonly authTokens: readonly { readonly token: string }[] };

const TOKEN: string = vectors.authTokens[0]?.token ?? "";

/**
 * The CloudFront interstitial. Not in `responses.json` — the capture ran from an address the CDN
 * did not block — so it is reproduced from `spec/05-rest-api.md` §1.2 and
 * `docs/protocol-notes.md` §8.2, which quote it.
 */
const CLOUDFRONT_HTML: string =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" ' +
  'CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n' +
  "</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n" +
  "<PRE>Generated by cloudfront (CloudFront)\nRequest ID: nUxjDe0-abcdefghijklmnop==</PRE>\n</BODY></HTML>";

const MAINNET: string = "https://mainnet.zklighter.elliot.ai";

/* ---------------------------------------------------------------------------------------------- */
/* Harness                                                                                          */
/* ---------------------------------------------------------------------------------------------- */

interface RecordedCall {
  readonly url: string;
  readonly method: string;
  readonly headers: Record<string, string>;
  readonly body: string | undefined;
  readonly signal: AbortSignal | undefined;
}

interface Stub {
  readonly fetch: typeof globalThis.fetch;
  readonly calls: RecordedCall[];
}

type Responder = (call: RecordedCall, index: number) => Response | Promise<Response>;

/** An injected `fetch` that records every call and answers from `responder`. */
function stubFetch(responder: Responder): Stub {
  const calls: RecordedCall[] = [];
  const fetchImpl = ((input: unknown, init?: RequestInit): Promise<Response> => {
    const headers: Record<string, string> = {};
    const raw: unknown = init?.headers;
    if (raw !== undefined && raw !== null) {
      for (const key of Object.keys(raw as Record<string, string>)) {
        headers[key] = (raw as Record<string, string>)[key] as string;
      }
    }
    const call: RecordedCall = {
      url: String(input),
      method: init?.method ?? "GET",
      headers,
      body: typeof init?.body === "string" ? init.body : undefined,
      signal: init?.signal ?? undefined,
    };
    calls.push(call);
    return Promise.resolve(responder(call, calls.length - 1)).then((r: Response): Response => r);
  }) as unknown as typeof globalThis.fetch;
  return { fetch: fetchImpl, calls };
}

/** A stub that replays a fixed script of responses, one per call. */
function scripted(...responses: readonly (() => Response)[]): Stub {
  return stubFetch((_call, index): Response => {
    const make: (() => Response) | undefined = responses[index];
    if (make === undefined) throw new Error(`unexpected call #${String(index + 1)}`);
    return make();
  });
}

function json(body: unknown, status: number = 200, headers: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", ...headers },
  });
}

function text(body: string, status: number, headers: Record<string, string> = {}): Response {
  return new Response(body, { status, headers: { "content-type": "text/html", ...headers } });
}

/** Backoff sleeps, captured instead of slept. */
function fakeSleep(): { sleep: (ms: number) => Promise<void>; delays: number[] } {
  const delays: number[] = [];
  return {
    sleep: (ms: number): Promise<void> => {
      delays.push(ms);
      return Promise.resolve();
    },
    delays,
  };
}

type Mutable = Record<string, unknown>;
const g: Mutable = globalThis as unknown as Mutable;

/**
 * Run `body` with browser-shaped globals installed.
 *
 * `request()` resolves its config **synchronously**, before its first `await`, so calling it inside
 * this block is enough to pin the environment; the returned promise is awaited outside, with the
 * globals already restored.
 */
function withGlobals<T>(entries: Record<string, unknown>, body: () => T): T {
  const saved = new Map<string, { had: boolean; value: unknown }>();
  for (const key of Object.keys(entries)) {
    saved.set(key, { had: key in g, value: g[key] });
    g[key] = entries[key];
  }
  try {
    return body();
  } finally {
    for (const [key, previous] of saved) {
      if (previous.had) g[key] = previous.value;
      else delete g[key];
    }
  }
}

/** Every route, by key, without the `as const` literal types getting in the way. */
const route: Record<string, RouteDef> = routes as unknown as Record<string, RouteDef>;

/* ---------------------------------------------------------------------------------------------- */
/* Classification                                                                                   */
/* ---------------------------------------------------------------------------------------------- */

describe("the success predicate", () => {
  test("a missing code is success — three endpoints send no code field at all", () => {
    // `/withdrawalDelay`, `/executeStats` and `/referral/points`. A check written as
    // `body.code === 200` rejects all three, which is the bug the Go reference ships.
    expect(isSuccess(200, undefined)).toBe(true);
    expect(isSuccess(200, 200)).toBe(true);
    expect(isSuccess(200, 21602)).toBe(false);
    expect(isSuccess(400, undefined)).toBe(false);
    expect(isSuccess(400, 29404)).toBe(false);
    expect(isSuccess(204, undefined)).toBe(true);
    expect(isSuccess(299, 200)).toBe(true);
    expect(isSuccess(300, 200)).toBe(false);
  });
});

describe("classifyResponse, against the captured responses", () => {
  test('(a) {"seconds":1805} with no code field is a success', () => {
    const captured: FixtureCase = fixture("withdrawalDelay-no-code-field");
    expect(captured.apiCode).toBeNull();

    const result = classifyResponse({
      status: captured.status,
      bodyText: JSON.stringify(captured.body),
      path: "/api/v1/withdrawalDelay",
    });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.body).toEqual({ seconds: 1805 });
  });

  test('(b) {"code":200,"order_books":[…]} is a success and the body passes through untouched', () => {
    const captured: FixtureCase = fixture("orderBooks");
    const result = classifyResponse({
      status: 200,
      bodyText: JSON.stringify(captured.body),
      path: "/api/v1/orderBooks",
    });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.body).toEqual(captured.body as Record<string, unknown>);
  });

  test("(c) HTTP 400 with code 29404 is an API error — not-found is never a 404", () => {
    const captured: FixtureCase = fixture("error-not-found");
    expect(captured.status).toBe(400);

    const result = classifyResponse({
      status: captured.status,
      bodyText: JSON.stringify(captured.body),
      path: "/api/v1/account",
      requestId: "cf-id-1",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    const error = result.error as LighterApiError;
    expect(isLighterApiError(error)).toBe(true);
    expect(error.code).toBe(29404);
    expect(error.status).toBe(400);
    expect(error.messageText).toBe("not found");
    expect(error.path).toBe("/api/v1/account");
    expect(error.requestId).toBe("cf-id-1");
    expect(error.body).toEqual(captured.body as Record<string, unknown>);
    expect(isLighterAuthError(error)).toBe(false);
  });

  test("(d) HTTP 401 with code 20013 is an auth error", () => {
    // Synthesised: the capture had no credential to expire. Shape from `spec` §4.2, which records
    // `20013` at HTTP 401 with three distinct messages.
    const result = classifyResponse({
      status: 401,
      bodyText: JSON.stringify({ code: 20013, message: "invalid auth: expired token" }),
      path: "/api/v1/accountActiveOrders",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    const error = result.error as LighterAuthError;
    expect(isLighterAuthError(error)).toBe(true);
    expect(error.kind).toBe("auth");
    expect(error.status).toBe(401);
    expect(error.code).toBe(20013);
    expect(error.reason).toBe("expired");
  });

  test("(d′) the three auth reasons the server actually distinguishes", () => {
    const reason = (message: string): string => {
      const r = classifyResponse({
        status: 401,
        bodyText: JSON.stringify({ code: 20013, message }),
        path: "/p",
      });
      return r.ok ? "" : (r.error as LighterAuthError).reason;
    };
    expect(reason("invalid auth: expired token")).toBe("expired");
    expect(reason("invalid auth: invalid auth string")).toBe("malformed");
    // Deliberately conflated by the server, presumably to avoid a signature oracle.
    expect(reason("invalid auth: invalid deadline")).toBe("deadline-or-signature");
  });

  test("(e) HTTP 403 with CloudFront HTML is a blocked error carrying the raw body", () => {
    const result = classifyResponse({
      status: 403,
      bodyText: CLOUDFRONT_HTML,
      path: "/api/v1/currentHeight",
      requestId: "cf-id-2",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    const error = result.error as LighterBlockedError;
    expect(error.kind).toBe("blocked");
    expect(error.rawBody).toBe(CLOUDFRONT_HTML);
    expect(error.status).toBe(403);
    expect(error.path).toBe("/api/v1/currentHeight");
    expect(error.requestId).toBe("cf-id-2");

    // No SyntaxError anywhere in the causal chain, and none in the serialised form either.
    let node: unknown = error;
    let depth: number = 0;
    while (node !== undefined && node !== null && depth < 10) {
      expect((node as { name?: unknown }).name).not.toBe("SyntaxError");
      expect(node instanceof SyntaxError).toBe(false);
      node = (node as { cause?: unknown }).cause;
      depth += 1;
    }
    expect(JSON.stringify(error.toJSON())).not.toContain("SyntaxError");
  });

  test("(f) HTTP 200 with a non-200 code is an API error — the two channels are independent", () => {
    const result = classifyResponse({
      status: 200,
      bodyText: JSON.stringify({ code: 21602, message: "invalid market index" }),
      path: "/api/v1/orderBookOrders",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect((result.error as LighterApiError).code).toBe(21602);
    expect((result.error as LighterApiError).status).toBe(200);
  });

  test("code 20558 is geo-restriction, with its own class and the message verbatim", () => {
    const captured: FixtureCase = fixture("error-geo-restricted");
    expect(captured.status).toBe(400);

    const result = classifyResponse({
      status: captured.status,
      bodyText: JSON.stringify(captured.body),
      path: "/api/v1/sendTx",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    const error = result.error as LighterGeoRestrictedError;
    expect(isLighterGeoRestrictedError(error)).toBe(true);
    expect(error.restricted).toBe(true);
    expect(error.name).toBe("LighterGeoRestrictedError");
    expect(error.code).toBe(20558);
    // Still an API error structurally: guards must keep working across bundler chunks.
    expect(isLighterApiError(error)).toBe(true);
    expect(error.messageText).toBe(
      "You are accessing Lighter from a restricted jurisdiction. For more information, see the https://lighter.xyz/terms",
    );
    // Never an auth error and never a bare validation failure.
    expect(isLighterAuthError(error)).toBe(false);
  });

  test("the invalid-param message keeps its trailing space, byte for byte", () => {
    const captured: FixtureCase = fixture("error-invalid-param");
    const result = classifyResponse({
      status: captured.status,
      bodyText: JSON.stringify(captured.body),
      path: "/api/v1/orderBookOrders",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    const error = result.error as LighterApiError;
    expect(error.messageText).toBe("invalid param ");
    expect(error.shortMessage).toBe("invalid param");
    expect(error.code).toBe(20001);
  });

  test("the missing-auth error is the discovery that documented the auth channel", () => {
    const captured: FixtureCase = fixture("error-missing-auth");
    const result = classifyResponse({
      status: captured.status,
      bodyText: JSON.stringify(captured.body),
      path: "/api/v1/transferFeeInfo",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect((result.error as LighterApiError).messageText).toBe(
      "invalid param : auth query param and Authorization header are empty",
    );
  });

  test("an unobserved code survives intact — the set is open", () => {
    const result = classifyResponse({
      status: 400,
      bodyText: JSON.stringify({ code: 31337, message: "something new" }),
      path: "/api/v1/whatever",
    });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect((result.error as LighterApiError).code).toBe(31337);
  });

  test("a non-2xx JSON body with no code at all still classifies, with code 0", () => {
    const result = classifyResponse({ status: 502, bodyText: '{"detail":"upstream"}', path: "/p" });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect((result.error as LighterApiError).code).toBe(0);
    expect((result.error as LighterApiError).status).toBe(502);
  });

  test("an empty body is a blocked error, never a thrown parse failure", () => {
    const result = classifyResponse({ status: 200, bodyText: "", path: "/p" });
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.kind).toBe("blocked");
  });

  test("classifyResponse is total: it never throws, whatever the body is", () => {
    for (const body of ["", "null", "[]", "{", "<html>", "0", '"a string"', "undefined"]) {
      expect(() => classifyResponse({ status: 200, bodyText: body, path: "/p" })).not.toThrow();
    }
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* URL and query serialisation                                                                      */
/* ---------------------------------------------------------------------------------------------- */

describe("query serialisation", () => {
  test("undefined and null keys are omitted entirely, not sent empty", () => {
    // Several endpoints treat an empty string differently from an absent key.
    const q = buildQuery({ market_id: 1, cursor: undefined, filter: null, limit: 5 });
    expect(q.toString()).toBe("market_id=1&limit=5");
    expect(q.has("cursor")).toBe(false);
    expect(q.has("filter")).toBe(false);
  });

  test("booleans are the lowercase literals", () => {
    expect(buildQuery({ a: true, b: false }).toString()).toBe("a=true&b=false");
  });

  test("numbers are plain decimal; bigints are exact", () => {
    expect(buildQuery({ n: 0, m: -7, f: 1.5 }).toString()).toBe("n=0&m=-7&f=1.5");
    expect(buildQuery({ big: 281474976710654n }).toString()).toBe("big=281474976710654");
    expect(buildQuery({ big: 9007199254740993n }).toString()).toBe("big=9007199254740993");
  });

  test("a number that would serialise in exponent form is refused, not sent", () => {
    // `String(5e21)` is "5e+21", which the server rejects as an invalid param.
    expect(() => buildQuery({ v: 5e21 })).toThrow(LighterValidationError);
    expect(() => buildQuery({ v: 1e-7 })).toThrow(LighterValidationError);
    expect(() => buildQuery({ v: 2 ** 53 })).toThrow(LighterValidationError);
    expect(() => buildQuery({ v: Number.NaN })).toThrow(LighterValidationError);
    expect(() => buildQuery({ v: Number.POSITIVE_INFINITY })).toThrow(LighterValidationError);
    try {
      buildQuery({ v: 5e21 });
    } catch (e: unknown) {
      expect((e as LighterValidationError).code).toBe("UNSAFE_INTEGER");
      expect((e as LighterValidationError).field).toBe("v");
    }
  });

  test("a structured value is refused: those travel as JSON strings in a single field", () => {
    expect(() => buildQuery({ v: { a: 1 } })).toThrow(LighterValidationError);
    expect(() => buildQuery({ v: [[1]] })).toThrow(LighterValidationError);
  });

  test("the two repeat-key array params emit repeated keys", () => {
    // `accountTxs.types` and `transfer/history.type` — the only two, both `style=form,explode=true`.
    const txs = buildUrl(route["accountTxs"] as RouteDef, { by: "account_index", value: "1", limit: 10, types: [14, 15] }, MAINNET);
    expect(txs).toBe(
      "https://mainnet.zklighter.elliot.ai/api/v1/accountTxs?by=account_index&value=1&limit=10&types=14&types=15",
    );

    const transfers = buildUrl(
      route["transferHistory"] as RouteDef,
      { account_index: 1, type: ["L2Transfer", "L2MintShares"] },
      MAINNET,
    );
    expect(transfers).toBe(
      "https://mainnet.zklighter.elliot.ai/api/v1/transfer/history?account_index=1&type=L2Transfer&type=L2MintShares",
    );

    expect(buildQuery({ types: [] }).toString()).toBe("");
  });

  test("the colons in a real auth token percent-encode and round-trip through URL", () => {
    const url: string = buildUrl(route["orderBooks"] as RouteDef, undefined, MAINNET, { auth: TOKEN });
    expect(TOKEN.split(":")).toHaveLength(4);
    expect(url).toContain("auth=");
    expect(url).not.toContain(`auth=${TOKEN}`); // the colons must be escaped
    expect(url).toContain("%3A");
    expect(new URL(url).searchParams.get("auth")).toBe(TOKEN);
  });
});

describe("buildUrl", () => {
  test("the base is an origin: /api/v1 lives on the route, and two routes sit at the root", () => {
    expect(buildUrl(route["orderBooks"] as RouteDef, undefined, MAINNET)).toBe(`${MAINNET}/api/v1/orderBooks`);
    expect(buildUrl(route["info"] as RouteDef, undefined, MAINNET)).toBe(`${MAINNET}/info`);
    expect(buildUrl(route["status"] as RouteDef, undefined, MAINNET)).toBe(`${MAINNET}/`);
  });

  test("trailing slashes on the base are stripped", () => {
    expect(stripTrailingSlash("https://h///")).toBe("https://h");
    expect(buildUrl(route["orderBooks"] as RouteDef, undefined, `${MAINNET}/`)).toBe(
      `${MAINNET}/api/v1/orderBooks`,
    );
  });

  test("a POST carries its parameters in the body, never in the query string", () => {
    expect(buildUrl(route["sendTx"] as RouteDef, { tx_type: 14, tx_info: "{}" }, MAINNET)).toBe(
      `${MAINNET}/api/v1/sendTx`,
    );
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Authentication                                                                                   */
/* ---------------------------------------------------------------------------------------------- */

describe("credential injection", () => {
  test("the Authorization header carries the token with no scheme prefix at all", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200, orders: [] }));
    await request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
      fetch: stub.fetch,
      auth: TOKEN,
    });
    const call: RecordedCall = stub.calls[0] as RecordedCall;
    expect(call.headers["Authorization"]).toBe(TOKEN);
    expect(call.headers["Authorization"]).not.toContain(" ");
    expect(call.url).not.toContain("auth=");
  });

  test("auth: 'none' routes send no credential in any channel", async () => {
    for (const key of ["sendTx", "sendTxBatch"]) {
      const target: RouteDef = route[key] as RouteDef;
      expect(target.auth).toBe("none");
      const stub: Stub = scripted((): Response => json({ code: 200 }));
      await request(target, { tx_type: 14, tx_info: "{}" }, { fetch: stub.fetch, auth: TOKEN });
      const call: RecordedCall = stub.calls[0] as RecordedCall;
      expect(call.headers["Authorization"]).toBeUndefined();
      expect(call.url).not.toContain("auth");
      expect(call.body ?? "").not.toContain("auth=");
    }
  });

  test("a route that requires auth fails fast when none is configured", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200 }));
    await expect(
      request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, { fetch: stub.fetch }),
    ).rejects.toBeInstanceOf(LighterConfigError);
    expect(stub.calls).toHaveLength(0);
  });

  test("an optional-auth route proceeds without a credential", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200, txs: [] }));
    await request(route["accountTxs"] as RouteDef, { by: "account_index", value: "1", limit: 1 }, {
      fetch: stub.fetch,
    });
    expect((stub.calls[0] as RecordedCall).headers["Authorization"]).toBeUndefined();
  });

  test("the provider receives the account index as advisory context", async () => {
    const seen: { accountIndex?: number }[] = [];
    const provider: AuthProvider = (ctx): string => {
      seen.push(ctx);
      return TOKEN;
    };
    const stub: Stub = scripted((): Response => json({ code: 200, orders: [] }));
    await request(route["accountActiveOrders"] as RouteDef, { account_index: 42 }, {
      fetch: stub.fetch,
      auth: provider,
    });
    expect(seen).toEqual([{ accountIndex: 42 }]);
  });

  test("the query channel is available, and the token still never lands on an error", async () => {
    const stub: Stub = scripted((): Response => json({ code: 20001, message: "invalid param " }, 400));
    let thrown: unknown;
    try {
      await request(route["transferFeeInfo"] as RouteDef, { account_index: 1 }, {
        fetch: stub.fetch,
        auth: TOKEN,
        authIn: "query",
      });
    } catch (e: unknown) {
      thrown = e;
    }
    const call: RecordedCall = stub.calls[0] as RecordedCall;
    expect(call.headers["Authorization"]).toBeUndefined();
    expect(new URL(call.url).searchParams.get("auth")).toBe(TOKEN);

    const error = thrown as LighterApiError;
    expect(error.path).toBe("/api/v1/transferFeeInfo");
    expect(error.path).not.toContain("?");
    expect(error.path).not.toContain("auth");
    expect(JSON.stringify(error.toJSON())).not.toContain(TOKEN);
  });

  test("no error, message or serialised form ever carries the token (D10)", async () => {
    const stub: Stub = scripted(
      (): Response => json({ code: 20001, message: `invalid param : rejected ${TOKEN}` }, 400),
    );
    let thrown: unknown;
    try {
      await request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
        fetch: stub.fetch,
        auth: TOKEN,
      });
    } catch (e: unknown) {
      thrown = e;
    }
    const error = thrown as LighterApiError;
    expect(error.path).not.toContain("?");
    expect(error.path).not.toContain("auth");
    // `messageText` is verbatim by contract; the *serialised* form is what must be safe.
    expect(error.messageText).toContain(TOKEN);
    const serialised: string = JSON.stringify(error.toJSON());
    expect(serialised).not.toContain(TOKEN);
    expect(serialised).toContain("[redacted]");
  });

  test("a provider that returns nothing usable is a config error, not a silent unauthenticated call", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200 }));
    await expect(
      request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
        fetch: stub.fetch,
        auth: ((): string => "") as AuthProvider,
      }),
    ).rejects.toBeInstanceOf(LighterConfigError);
    expect(stub.calls).toHaveLength(0);
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Bodies                                                                                           */
/* ---------------------------------------------------------------------------------------------- */

describe("body encoding", () => {
  test("form encoding for sendTx — 17 of the 18 POSTs", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200, tx_hash: "0xabc" }));
    await request(route["sendTx"] as RouteDef, { tx_type: 14, tx_info: '{"a":1}' }, { fetch: stub.fetch });
    const call: RecordedCall = stub.calls[0] as RecordedCall;
    expect(call.method).toBe("POST");
    expect(call.headers["Content-Type"]).toBe("application/x-www-form-urlencoded");
    expect(call.body).toBe("tx_type=14&tx_info=%7B%22a%22%3A1%7D");
    expect(new URLSearchParams(call.body ?? "").get("tx_info")).toBe('{"a":1}');
  });

  test("JSON encoding for setAccountMetadata — the single exception", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200 }));
    await request(route["setAccountMetadata"] as RouteDef, { account_index: 1, name: "bot" }, {
      fetch: stub.fetch,
    });
    const call: RecordedCall = stub.calls[0] as RecordedCall;
    expect(call.headers["Content-Type"]).toBe("application/json");
    expect(call.body).toBe('{"account_index":1,"name":"bot"}');
  });

  test("the CDN interstitial reaches the caller as a blocked error, end to end", async () => {
    // The whole point of reading the body as text once: this path must not produce a parse failure,
    // and it must not consume the read we need for `rawBody`.
    const stub: Stub = scripted((): Response => text(CLOUDFRONT_HTML, 403, { "x-amz-cf-id": "cf-3" }));
    let thrown: unknown;
    try {
      await request(route["currentHeight"] as RouteDef, undefined, { fetch: stub.fetch });
    } catch (e: unknown) {
      thrown = e;
    }
    expect(thrown).toBeInstanceOf(LighterBlockedError);
    const error = thrown as LighterBlockedError;
    expect(error.rawBody).toBe(CLOUDFRONT_HTML);
    expect(error.status).toBe(403);
    expect(error.requestId).toBe("cf-3");
    expect(error.path).toBe("/api/v1/currentHeight");
    // 403 is IP-reputation based, not transient: repeating it just repeats the answer.
    expect(stub.calls).toHaveLength(1);
  });

  test("a GET sends no body and no Content-Type", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200, order_books: [] }));
    await request(route["orderBooks"] as RouteDef, undefined, { fetch: stub.fetch });
    const call: RecordedCall = stub.calls[0] as RecordedCall;
    expect(call.body).toBeUndefined();
    expect(call.headers["Content-Type"]).toBeUndefined();
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Retry                                                                                            */
/* ---------------------------------------------------------------------------------------------- */

describe("backoff arithmetic", () => {
  test("full jitter, exponential, capped", () => {
    const policy = { baseMs: 200, capMs: 5_000 };
    // random() === 1 is the top of each window, which is what makes the growth visible.
    expect(retryDelayMs(0, policy, undefined, () => 1)).toBe(200);
    expect(retryDelayMs(1, policy, undefined, () => 1)).toBe(400);
    expect(retryDelayMs(2, policy, undefined, () => 1)).toBe(800);
    expect(retryDelayMs(9, policy, undefined, () => 1)).toBe(5_000);
    // Full jitter: the whole window is in play, not a fixed delay plus noise.
    expect(retryDelayMs(3, policy, undefined, () => 0)).toBe(0);
    expect(retryDelayMs(3, policy, undefined, () => 0.5)).toBe(800);
  });

  test("Retry-After wins over the computed delay, clamped to the cap", () => {
    const policy = { baseMs: 200, capMs: 5_000 };
    expect(retryDelayMs(0, policy, 1_000, () => 1)).toBe(1_000);
    expect(retryDelayMs(0, policy, 120_000, () => 1)).toBe(5_000);
  });

  test("Retry-After parses both RFC forms and shrugs off anything else", () => {
    expect(parseRetryAfterMs("2", 0)).toBe(2_000);
    expect(parseRetryAfterMs("0", 0)).toBe(0);
    expect(parseRetryAfterMs(null, 0)).toBeUndefined();
    expect(parseRetryAfterMs("soon", 0)).toBeUndefined();
    expect(parseRetryAfterMs("", 0)).toBeUndefined();
    const now: number = Date.parse("Wed, 21 Oct 2015 07:28:00 GMT");
    expect(parseRetryAfterMs("Wed, 21 Oct 2015 07:28:03 GMT", now)).toBe(3_000);
    expect(parseRetryAfterMs("Wed, 21 Oct 2015 07:27:00 GMT", now)).toBe(0);
  });

  test("only 429 and 5xx are worth repeating", () => {
    expect(isRetryableStatus(429)).toBe(true);
    expect(isRetryableStatus(500)).toBe(true);
    expect(isRetryableStatus(503)).toBe(true);
    expect(isRetryableStatus(400)).toBe(false);
    expect(isRetryableStatus(401)).toBe(false);
    expect(isRetryableStatus(403)).toBe(false);
    expect(isRetryableStatus(200)).toBe(false);
  });
});

describe("retry policy", () => {
  test("a GET retries 429 then 503, with growing jittered delays", async () => {
    const stub: Stub = scripted(
      (): Response => json({ code: 20001, message: "rate limited" }, 429),
      (): Response => json({ code: 20001, message: "bad gateway" }, 503),
      (): Response => json({ code: 200, order_books: [] }),
    );
    const timer = fakeSleep();
    const body = await request(route["orderBooks"] as RouteDef, undefined, {
      fetch: stub.fetch,
      sleep: timer.sleep,
      random: (): number => 1,
    });
    expect(stub.calls).toHaveLength(3);
    expect(timer.delays).toEqual([200, 400]);
    expect(body).toEqual({ code: 200, order_books: [] });
  });

  test("Retry-After on a 429 is honoured", async () => {
    const stub: Stub = scripted(
      (): Response => json({ code: 20001 }, 429, { "retry-after": "2" }),
      (): Response => json({ code: 200, order_books: [] }),
    );
    const timer = fakeSleep();
    await request(route["orderBooks"] as RouteDef, undefined, {
      fetch: stub.fetch,
      sleep: timer.sleep,
      random: (): number => 0,
    });
    expect(timer.delays).toEqual([2_000]);
  });

  test("the budget is exhausted after `attempts` retries and the last error propagates", async () => {
    const stub: Stub = stubFetch((): Response => json({ code: 20001, message: "down" }, 503));
    const timer = fakeSleep();
    await expect(
      request(route["orderBooks"] as RouteDef, undefined, {
        fetch: stub.fetch,
        sleep: timer.sleep,
        retry: { attempts: 2 },
      }),
    ).rejects.toBeInstanceOf(LighterApiError);
    expect(stub.calls).toHaveLength(3); // the original plus two retries
  });

  test("attempts: 0 disables retrying", async () => {
    const stub: Stub = stubFetch((): Response => json({ code: 20001 }, 503));
    await expect(
      request(route["orderBooks"] as RouteDef, undefined, { fetch: stub.fetch, retry: { attempts: 0 } }),
    ).rejects.toBeInstanceOf(LighterApiError);
    expect(stub.calls).toHaveLength(1);
  });

  test("a 400 is never retried", async () => {
    const stub: Stub = stubFetch((): Response => json(fixture("error-not-found").body, 400));
    await expect(
      request(route["account"] as RouteDef, { by: "index", value: "999999999999" }, { fetch: stub.fetch }),
    ).rejects.toBeInstanceOf(LighterApiError);
    expect(stub.calls).toHaveLength(1);
  });

  test("a transport failure is retried; a caller's abort is not", async () => {
    let calls: number = 0;
    const stub: Stub = stubFetch((): Response => {
      calls += 1;
      if (calls < 3) throw new TypeError("fetch failed");
      return json({ code: 200, order_books: [] });
    });
    const timer = fakeSleep();
    await request(route["orderBooks"] as RouteDef, undefined, { fetch: stub.fetch, sleep: timer.sleep });
    expect(calls).toBe(3);
  });

  test("a POST is never retried, under any status", async () => {
    // `sendTx` is nonce-bound: a duplicate submission is a real economic loss, not untidiness.
    for (const status of [429, 500, 503]) {
      const stub: Stub = stubFetch((): Response => json({ code: 20001, message: "no" }, status));
      await expect(
        request(route["sendTx"] as RouteDef, { tx_type: 14, tx_info: "{}" }, { fetch: stub.fetch }),
      ).rejects.toBeInstanceOf(LighterApiError);
      expect(stub.calls).toHaveLength(1);
    }
    // Including a transport failure, where nothing is known to have reached the origin.
    const flaky: Stub = stubFetch((): Response => {
      throw new TypeError("connection reset");
    });
    await expect(
      request(route["sendTx"] as RouteDef, { tx_type: 14, tx_info: "{}" }, { fetch: flaky.fetch }),
    ).rejects.toBeInstanceOf(LighterTransportError);
    expect(flaky.calls).toHaveLength(1);
    // And a 401 on an auth-less write is not replayed either: no credential was attached.
    const refused: Stub = stubFetch((): Response => json({ code: 20013, message: "invalid auth" }, 401));
    await expect(
      request(route["sendTx"] as RouteDef, { tx_type: 14, tx_info: "{}" }, {
        fetch: refused.fetch,
        auth: TOKEN,
      }),
    ).rejects.toBeInstanceOf(LighterAuthError);
    expect(refused.calls).toHaveLength(1);
  });
});

describe("the bounded auth replay", () => {
  test("a 20013 re-invokes the provider exactly once and replays exactly once", async () => {
    let minted: number = 0;
    const provider: AuthProvider = (): string => {
      minted += 1;
      return `${TOKEN}${String(minted)}`;
    };
    const stub: Stub = scripted(
      (): Response => json({ code: 20013, message: "invalid auth: expired token" }, 401),
      (): Response => json({ code: 200, orders: [] }),
    );
    const body = await request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
      fetch: stub.fetch,
      auth: provider,
    });
    expect(minted).toBe(2);
    expect(stub.calls).toHaveLength(2);
    expect((stub.calls[0] as RecordedCall).headers["Authorization"]).toBe(`${TOKEN}1`);
    expect((stub.calls[1] as RecordedCall).headers["Authorization"]).toBe(`${TOKEN}2`);
    expect(body).toEqual({ code: 200, orders: [] });
  });

  test("one replay, then the error propagates", async () => {
    let minted: number = 0;
    const provider: AuthProvider = (): string => {
      minted += 1;
      return TOKEN;
    };
    const stub: Stub = stubFetch(
      (): Response => json({ code: 20013, message: "invalid auth: invalid deadline" }, 401),
    );
    await expect(
      request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
        fetch: stub.fetch,
        auth: provider,
      }),
    ).rejects.toBeInstanceOf(LighterAuthError);
    expect(stub.calls).toHaveLength(2);
    expect(minted).toBe(2);
  });

  test("the replay does not consume the retry budget, and is not a backoff", async () => {
    const timer = fakeSleep();
    const stub: Stub = scripted(
      (): Response => json({ code: 20013, message: "invalid auth: expired token" }, 401),
      (): Response => json({ code: 20001, message: "down" }, 503),
      (): Response => json({ code: 20001, message: "down" }, 503),
      (): Response => json({ code: 200, orders: [] }),
    );
    await request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
      fetch: stub.fetch,
      auth: TOKEN,
      sleep: timer.sleep,
      random: (): number => 1,
    });
    expect(stub.calls).toHaveLength(4);
    expect(timer.delays).toEqual([200, 400]);
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Timeouts and cancellation                                                                        */
/* ---------------------------------------------------------------------------------------------- */

describe("timeouts", () => {
  test("a fetch that never settles fails with a timeout inside the budget", async () => {
    // Deliberately ignores its signal: the budget must hold even against a `fetch` that does not
    // honour aborts, which is why the implementation races the signal rather than trusting it.
    const stub: Stub = stubFetch((): Promise<Response> => new Promise<Response>((): void => {}));
    const started: number = Date.now();
    await expect(
      request(route["orderBooks"] as RouteDef, undefined, { fetch: stub.fetch, timeoutMs: 40 }),
    ).rejects.toBeInstanceOf(LighterTimeoutError);
    expect(Date.now() - started).toBeLessThan(2_000);
  });

  test("the timeout error is retryable, so a GET spends its whole budget", async () => {
    const stub: Stub = stubFetch((): Promise<Response> => new Promise<Response>((): void => {}));
    const timer = fakeSleep();
    await expect(
      request(route["orderBooks"] as RouteDef, undefined, {
        fetch: stub.fetch,
        timeoutMs: 20,
        sleep: timer.sleep,
        retry: { attempts: 1 },
      }),
    ).rejects.toBeInstanceOf(LighterTimeoutError);
    expect(stub.calls).toHaveLength(2);
  });

  test("writes get the longer budget by default", async () => {
    // 10 s reads, 30 s writes. Asserted through the config rather than by waiting.
    const stub: Stub = scripted((): Response => json({ code: 200 }));
    await request(route["sendTx"] as RouteDef, { tx_type: 14, tx_info: "{}" }, { fetch: stub.fetch });
    expect((stub.calls[0] as RecordedCall).signal).toBeDefined();
  });

  test("a caller-supplied signal aborts the request, and is not retried", async () => {
    const controller: AbortController = new AbortController();
    const stub: Stub = stubFetch((): Promise<Response> => new Promise<Response>((): void => {}));
    const pending = request(route["orderBooks"] as RouteDef, undefined, {
      fetch: stub.fetch,
      signal: controller.signal,
    });
    controller.abort();
    let thrown: unknown;
    try {
      await pending;
    } catch (e: unknown) {
      thrown = e;
    }
    expect(thrown).toBeInstanceOf(LighterTransportError);
    expect(thrown).not.toBeInstanceOf(LighterTimeoutError);
    expect((thrown as LighterTransportError).retryable).toBe(false);
    expect(stub.calls).toHaveLength(1);
  });

  test("an already-aborted signal fails immediately", async () => {
    const stub: Stub = stubFetch((): Response => json({ code: 200 }));
    await expect(
      request(route["orderBooks"] as RouteDef, undefined, {
        fetch: stub.fetch,
        signal: AbortSignal.abort(),
      }),
    ).rejects.toBeInstanceOf(LighterTransportError);
  });

  test("the composed signal reaches fetch", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200, order_books: [] }));
    await request(route["orderBooks"] as RouteDef, undefined, { fetch: stub.fetch });
    const signal: AbortSignal | undefined = (stub.calls[0] as RecordedCall).signal;
    expect(signal).toBeInstanceOf(AbortSignal);
    expect(signal?.aborted).toBe(false);
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* raw                                                                                              */
/* ---------------------------------------------------------------------------------------------- */

describe("raw", () => {
  test("raw: true returns the Response with its body unread", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200, order_books: [] }));
    const response: Response = await request(route["orderBooks"] as RouteDef, undefined, {
      fetch: stub.fetch,
      raw: true,
    });
    expect(response).toBeInstanceOf(Response);
    expect(response.bodyUsed).toBe(false);
    expect(await response.json()).toEqual({ code: 200, order_books: [] });
  });

  test("raw: true does not classify — a 400 comes back as a Response, not a throw", async () => {
    const stub: Stub = scripted((): Response => json(fixture("error-not-found").body, 400));
    const response: Response = await request(route["account"] as RouteDef, { by: "index", value: "1" }, {
      fetch: stub.fetch,
      raw: true,
    });
    expect(response.status).toBe(400);
    expect(response.bodyUsed).toBe(false);
  });

  test("raw: true still retries a 5xx GET", async () => {
    const stub: Stub = scripted(
      (): Response => json({ code: 20001 }, 503),
      (): Response => json({ code: 200, order_books: [] }),
    );
    const timer = fakeSleep();
    const response: Response = await request(route["orderBooks"] as RouteDef, undefined, {
      fetch: stub.fetch,
      raw: true,
      sleep: timer.sleep,
    });
    expect(stub.calls).toHaveLength(2);
    expect(response.status).toBe(200);
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Header policy                                                                                    */
/* ---------------------------------------------------------------------------------------------- */

describe("header policy (docs/decisions.md D5)", () => {
  const ALLOWED: ReadonlySet<string> = new Set<string>([
    "content-type",
    "origin",
    "x-csrf-token",
    "authorization",
    "accesstoken",
    "token",
    "range",
  ]);

  test("in a browser environment no User-Agent is set and nothing leaves the CORS allow-list", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200, orders: [] }));
    // `request()` resolves its config synchronously, so pinning the globals across the call
    // expression is enough; the promise is awaited with the environment already restored.
    const pending = withGlobals({ document: {}, window: {} }, () =>
      request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
        fetch: stub.fetch,
        auth: TOKEN,
        userAgent: "explicitly-requested/1.0",
      }),
    );
    await pending;
    const call: RecordedCall = stub.calls[0] as RecordedCall;
    expect(call.headers["User-Agent"]).toBeUndefined();
    expect(Object.keys(call.headers)).toEqual(["Authorization"]);
    for (const name of Object.keys(call.headers)) {
      expect(ALLOWED.has(name.toLowerCase())).toBe(true);
    }
  });

  test("a browser POST sends only Authorization and Content-Type", async () => {
    const stub: Stub = scripted((): Response => json({ code: 200 }));
    await withGlobals({ document: {}, window: {} }, () =>
      request(route["setAccountMetadata"] as RouteDef, { account_index: 1 }, {
        fetch: stub.fetch,
        auth: TOKEN,
      }),
    );
    const names: string[] = Object.keys((stub.calls[0] as RecordedCall).headers).sort();
    expect(names).toEqual(["Authorization", "Content-Type"]);
  });

  test("outside a browser a browser-like User-Agent is set, and is configurable", async () => {
    const stub: Stub = scripted(
      (): Response => json({ code: 200, order_books: [] }),
      (): Response => json({ code: 200, order_books: [] }),
    );
    await request(route["orderBooks"] as RouteDef, undefined, { fetch: stub.fetch });
    expect((stub.calls[0] as RecordedCall).headers["User-Agent"]).toContain("Mozilla/5.0");

    await request(route["orderBooks"] as RouteDef, undefined, {
      fetch: stub.fetch,
      userAgent: "my-bot/1.0",
    });
    expect((stub.calls[1] as RecordedCall).headers["User-Agent"]).toBe("my-bot/1.0");
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Diagnostics                                                                                      */
/* ---------------------------------------------------------------------------------------------- */

describe("diagnostics", () => {
  test("every line is redacted and named by a stable dotted event", async () => {
    const seen: Diagnostic[] = [];
    const stub: Stub = scripted(
      (): Response => json({ code: 20001 }, 429),
      (): Response => json({ code: 200, orders: [] }),
    );
    const timer = fakeSleep();
    await request(route["accountActiveOrders"] as RouteDef, { account_index: 1 }, {
      fetch: stub.fetch,
      auth: TOKEN,
      sleep: timer.sleep,
      onDiagnostic: (d: Diagnostic): void => {
        seen.push(d);
      },
    });
    const events: string[] = seen.map((d: Diagnostic): string => d.event);
    expect(events).toContain("rest.request");
    expect(events).toContain("rest.retry");
    expect(JSON.stringify(seen)).not.toContain(TOKEN);
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Inference                                                                                        */
/* ---------------------------------------------------------------------------------------------- */

describe("type inference through the route table", () => {
  test("params and response are inferred from the route, with no annotation at the call site", async () => {
    const stub: Stub = scripted(
      (): Response => json(fixture("orderBooks").body),
      (): Response => json({ seconds: 1805 }),
      (): Response => json({ code: 200, tx_hash: "0xdead" }),
    );

    // `routes.orderBooks` keeps its literal type, so `market_id` is checked and the result is
    // `OrderBooks` — not `unknown`, and not a cast.
    const books: OrderBooks = await request(routes.orderBooks, { market_id: 1 }, { fetch: stub.fetch });
    expect(books.order_books?.length).toBe(3);

    // The envelope-breaking endpoint: no `code` field on the model at all.
    const delay: RespWithdrawalDelay = await request(
      routes.withdrawalDelay,
      { account_index: 1 },
      { fetch: stub.fetch },
    );
    expect(delay.seconds).toBe(1805);

    const sent: RespSendTx = await request(
      routes.sendTx,
      { tx_type: 14, tx_info: "{}" },
      { fetch: stub.fetch },
    );
    expect(sent.tx_hash).toBe("0xdead");

    // `raw: true` narrows the return type to `Response` through the overload.
    const rawStub: Stub = scripted((): Response => json({ code: 200 }));
    const response: Response = await request(routes.orderBooks, undefined, {
      fetch: rawStub.fetch,
      raw: true,
    });
    expect(response.status).toBe(200);
  });
});

/* ---------------------------------------------------------------------------------------------- */
/* Hygiene                                                                                          */
/* ---------------------------------------------------------------------------------------------- */

describe("hygiene", () => {
  const source: string = readFileSync(
    new URL("../../src/rest/transport.ts", import.meta.url),
    "utf8",
  );

  test("no Node built-in, no environment sniffing, and the body is read as text", () => {
    for (const forbidden of ["node:", "Buffer", "process.", "require(", ".json()"]) {
      expect(source).not.toContain(forbidden);
    }
  });

  test("the credential is sent with no scheme prefix", () => {
    expect(source).not.toContain("Bearer");
  });

  test("importing the transport touches no global, clock, timer or network", () => {
    const entry: string = new URL("../../src/rest/transport.ts", import.meta.url).pathname;
    const probe: string = [
      "const touched = [];",
      'for (const k of ["fetch","WebSocket","document","window","navigator","crypto","XMLHttpRequest"]) {',
      '  try { Object.defineProperty(globalThis, k, { configurable: true, get() { touched.push(k); throw new Error("read global " + k); } }); }',
      '  catch { touched.push("unstubbable:" + k); }',
      "}",
      'Date.now = () => { touched.push("Date.now"); throw new Error("clock"); };',
      'for (const k of ["setTimeout","setInterval","queueMicrotask"]) {',
      "  const original = globalThis[k];",
      "  globalThis[k] = (...args) => { touched.push(k); return original(...args); };",
      "}",
      `const m = await import(${JSON.stringify(entry)});`,
      'if (typeof m.request !== "function") { console.log("MISSING_EXPORT"); }',
      'else console.log(touched.length === 0 ? "CLEAN" : "TOUCHED:" + touched.join(","));',
    ].join("\n");

    const proc = Bun.spawnSync(["bun", "-e", probe], { stdout: "pipe", stderr: "pipe" });
    const stdout: string = proc.stdout.toString().trim();
    const stderr: string = proc.stderr.toString().trim();
    expect(`${stdout}${stderr === "" ? "" : ` | stderr: ${stderr}`}`).toBe("CLEAN");
    expect(proc.exitCode).toBe(0);
  });
});
