/**
 * `lighter-ts` — the root barrel.
 *
 * This file is re-exports and nothing else. No expression is evaluated when it loads: no `new`, no
 * constant construction, no clock read, no `crypto.getRandomValues` (which Cloudflare Workers
 * forbids at module scope, `docs/protocol-notes.md` §5.1), no top-level `await`. That is what makes
 * `"sideEffects": false` in `package.json` a true statement rather than a hopeful one, and
 * `test/portability/behaviour.ts` asserts it instead of trusting it.
 *
 * ## Prefer the subpaths
 *
 * ```ts
 * import { ApiKey } from "lighter-ts/crypto";
 * import { buildCreateOrder, signTx } from "lighter-ts/tx";
 * ```
 *
 * Importing from `"lighter-ts"` pulls the whole module graph into a bundler's reachability set
 * before tree-shaking, because this file names every module. The subpath entries in the `exports`
 * map (`./crypto`, `./tx`, `./rest`, `./ws`, `./client`, `./config`, `./errors`) cost a fraction of
 * it. The root barrel exists for scripts, examples and REPLs, where one import beats seven.
 *
 * ## Why every name is written out
 *
 * `export * from` is shorter and wrong here. When two modules export the same name, a star export
 * drops it from the barrel **silently** — no error, no warning, just a name that no longer exists.
 * Fifteen names collide across these modules, so fifteen names would have vanished. Writing the
 * list out costs a thousand lines and makes the published surface reviewable in one file.
 *
 * The list is mechanical: it is every export of every module below, minus the fifteen losers of the
 * collisions in the table. Two rules decide each one.
 *
 * 1. **A value beats a type-only name.** Dropping a value removes a capability; dropping a type
 *    removes only a name, and the shape is still describable structurally.
 * 2. **Otherwise, module order decides** — `errors`, `config`, `crypto`, `tx`, `rest`, `ws`,
 *    `client` — *except* that a type from `src/models/**` beats a type from a subpath. The models
 *    have no subpath of their own (there is no `src/models/index.ts`, so `package.json` exposes no
 *    `./models` entry), which makes this barrel the only place their names are importable. A
 *    subpath's name that loses here is still one `import … from "lighter-ts/<subpath>"` away.
 *
 * | Name | Root gives you | The other one, still reachable at |
 * | --- | --- | --- |
 * | `ApiKey` | `crypto` — the signing key class | nowhere: the REST API-key record in `src/models/account.ts` is not re-exported |
 * | `DEFAULT_TX_EXPIRY_MS` | `config` | `lighter-ts/tx` — same literal `599_000` |
 * | `WebSocketLike`, `WebSocketConstructor` | `config` | `lighter-ts/ws` — structurally identical declarations |
 * | `NIL_MARKET_INDEX` | `tx` | `lighter-ts/client` — same literal `255` |
 * | `expiryIn` | `tx` — returns `I64` | `lighter-ts/client` — returns `bigint`, accepts seconds and ms |
 * | `OrderType`, `AssetMarginMode` | `tx` — the numeric protocol codes | nowhere: the REST string unions in `src/models/` are not re-exported |
 * | `MarketKind` | models — `"perp" \| "spot"`, the wire value | `lighter-ts/tx` — `"perps" \| "spot"`, the index-range classifier |
 * | `Side` | models — `"all" \| "long" \| "short"`, a query filter | `lighter-ts/client` — `"buy" \| "sell"`, an order direction |
 * | `Order`, `Trade`, `Candle`, `AccountAsset`, `PositionFunding` | models — the REST shapes | `lighter-ts/ws` — the stream shapes, which differ |
 *
 * Three names lose in both directions and are reachable from nowhere in the published package:
 * the model `ApiKey`, `OrderType` and `AssetMarginMode` records. They are REST response types; a
 * caller reads them off a route's return type rather than by name. Adding `src/models/index.ts`
 * and a `./models` subpath would fix that, and it belongs to whichever unit takes ownership of
 * that file — not to this one (`docs/decisions.md` D8: one owner per path).
 *
 * ## What is not here
 *
 * - **`./paper`** — the paper-trading engine is cut from v1 (D10): no conformance vectors exist for
 *   it, so no unit could be verified independently.
 * - **`./l1-signer`** — there is no secp256k1, keccak256 or RFC-6979 in this package (D6). The SDK
 *   builds the exact EIP-191 message and takes the signature from an injected `L1Signer`; the
 *   message bodies are pinned in `conformance/vectors/tx.json` under `l1Messages`.
 * - **`src/util/**`** — internal. Nothing in `docs/ARCHITECTURE.md` §6 exposes it.
 *
 * Regenerating this list after a subpath gains an export is a mechanical job, and until it happens
 * the new name is reachable from its subpath and not from the root.
 */

/* ------------------------------------------------------------------------------------------------ */
/* The error hierarchy — also `lighter-ts/errors` */
/* ------------------------------------------------------------------------------------------------ */
export {
  ERR_ACCOUNT_NOT_FOUND,
  ERR_INVALID_AUTH,
  ERR_INVALID_MARKET_INDEX,
  ERR_INVALID_PARAM,
  ERR_NOT_FOUND,
  ERR_RESTRICTED_JURISDICTION,
  ERR_TIME_RANGE_EXCEEDED,
  ERR_TX_NOT_FOUND,
  L1SignatureRequiredError,
  LighterApiError,
  LighterAuthError,
  LighterBlockedError,
  LighterConfigError,
  LighterError,
  LighterMathError,
  LighterNonceError,
  LighterSignatureError,
  LighterTimeoutError,
  LighterTransportError,
  LighterValidationError,
  RESULT_OK,
  hasCode,
  isLighterApiError,
  isLighterAuthError,
  isLighterError,
  isRetryable,
} from "./errors.js";
export type {
  L1SignatureRequiredErrorOptions,
  LighterApiErrorOptions,
  LighterAuthErrorOptions,
  LighterAuthReason,
  LighterBlockedErrorOptions,
  LighterErrorKind,
  LighterErrorOptions,
  LighterMathCode,
  LighterNonceCode,
  LighterTransportErrorOptions,
  LighterValidationCode,
  LighterValidationErrorOptions,
} from "./errors.js";

/* ------------------------------------------------------------------------------------------------ */
/* Configuration and endpoint profiles — also `lighter-ts/config` */
/* ------------------------------------------------------------------------------------------------ */
export {
  DEFAULT_TX_EXPIRY_MS,
  DEFAULT_USER_AGENT,
  defineProfile,
  getProfile,
  isBrowserLike,
  profiles,
  resolveConfig,
} from "./config/index.js";
export type {
  AuthProvider,
  Diagnostic,
  EndpointProfile,
  LighterConfig,
  ProfileMap,
  ProfileName,
  ResolvedConfig,
  WebSocketConstructor,
  WebSocketLike,
} from "./config/index.js";

/* ------------------------------------------------------------------------------------------------ */
/* Field, curve, Poseidon2, Schnorr, keys — also `lighter-ts/crypto` */
/* ------------------------------------------------------------------------------------------------ */
export {
  ApiKey,
  CAPACITY,
  CURVE_A,
  CURVE_B,
  EMPTY_HASH_OUT,
  EPSILON,
  FP5_DTH_ROOT,
  FP5_ONE,
  FP5_TWO,
  FP5_W,
  FP5_ZERO,
  FP_NEG_ONE,
  FP_ONE,
  FP_TWO,
  FP_ZERO,
  FROB1,
  FROB2,
  FROB3,
  FROB4,
  GENERATOR,
  HASH_BYTES,
  MASK32,
  MASK64,
  MULTIPLICATIVE_GENERATOR,
  N,
  NEUTRAL,
  OUT,
  P,
  POWER_OF_TWO_GENERATOR,
  PUBKEY_BYTES,
  RATE,
  ROUNDS_F,
  ROUNDS_P,
  SCALAR_BYTES,
  SIGNATURE_BYTES,
  TWO_ADICITY,
  WIDTH,
  WINDOW,
  WINDOW_SIZE,
  batchToAffine,
  challenge,
  chooseNonce,
  decodePoint,
  deriveNonceHedged,
  encodePoint,
  fp5Add,
  fp5CanonicalSqrt,
  fp5Div,
  fp5Double,
  fp5Equals,
  fp5ExpPow2,
  fp5Frobenius,
  fp5FromBytes,
  fp5FromBytesStrict,
  fp5FromFp,
  fp5FromLimbs,
  fp5FromU64,
  fp5Inverse,
  fp5InverseOrZero,
  fp5IsZero,
  fp5Legendre,
  fp5Mul,
  fp5Neg,
  fp5Norm,
  fp5RepeatedFrobenius,
  fp5ScalarMul,
  fp5Sgn0,
  fp5Sqrt,
  fp5Square,
  fp5Sub,
  fp5ToBytes,
  fp5Triple,
  fpAdd,
  fpArrayFromBytes,
  fpArrayToBytes,
  fpBatchInverse,
  fpDouble,
  fpExp,
  fpExpPow2,
  fpFromBytes,
  fpFromBytesUnchecked,
  fpFromInt,
  fpFromU64,
  fpInverse,
  fpInverseOrZero,
  fpIsQuadraticResidue,
  fpMul,
  fpMulAcc,
  fpNeg,
  fpPowers,
  fpSqrt,
  fpSquare,
  fpSub,
  fpToBytes,
  generatorWindow,
  generatorWindowIsBuilt,
  hashNToM,
  hashNToOne,
  hashNoPad,
  hashOutFromLeBytes,
  hashOutToLeBytes,
  hashToQuinticExtension,
  hashTwoToOne,
  lookupWindow,
  lookupWindowVarTime,
  makeWindow,
  modN,
  mulAddG,
  mulGenerator,
  mulScalar,
  permute,
  pointAdd,
  pointAddAffine,
  pointDouble,
  pointDoubleN,
  pointEquals,
  pointIsNeutral,
  pointIsOnCurve,
  pointNegate,
  pointToAffine,
  publicKeyFromPrivateKey,
  randomNonce,
  recodeScalar5,
  recodeSigned5,
  recodeSignedDigits,
  reduce128,
  reduceWide,
  scalarAdd,
  scalarFromBytes,
  scalarFromBytesStrict,
  scalarFromFp5,
  scalarIsCanonicalBytes,
  scalarMul,
  scalarNeg,
  scalarSub,
  scalarToBytes,
  signHashed,
  signatureFromBytes,
  signatureToBytes,
  verify,
  windowIsWellFormed,
} from "./crypto/index.js";
export type {
  AffinePoint,
  CurvePoint,
  Fp,
  Fp5,
  Fp5Like,
  HashOut,
  NonceMode,
  NonceOption,
  Scalar,
  SignOptions,
  Signature,
  State,
} from "./crypto/index.js";

/* ------------------------------------------------------------------------------------------------ */
/* Transaction vocabulary, builders, hashing, signing — also `lighter-ts/tx` */
/* ------------------------------------------------------------------------------------------------ */
export {
  ACCOUNT_TX_SCHEMAS,
  ACCOUNT_TX_SCHEMA_LIST,
  API_MAX_ORDER_TYPE,
  APPROVE_INTEGRATOR_SCHEMA,
  ATTRIBUTES_JSON_KEY,
  ATTRIBUTE_REGISTRY,
  AccountAssetMarginMode,
  AccountTradingMode,
  AssetMarginMode,
  AssetRouteType,
  BURN_SHARES_SCHEMA,
  CANCEL_ALL_ORDERS_SCHEMA,
  CANCEL_ORDER_SCHEMA,
  CHAIN_ID,
  CHANGE_PUB_KEY_SCHEMA,
  CONSTRUCTIBLE_TX_TYPES,
  CREATE_GROUPED_ORDERS_SCHEMA,
  CREATE_ORDER_SCHEMA,
  CREATE_PUBLIC_POOL_SCHEMA,
  CREATE_SUB_ACCOUNT_SCHEMA,
  CancelAllTimeInForce,
  DEFAULT_STRATEGY_INDEX,
  EIP191_PREFIX,
  FEE_TICK,
  GroupingType,
  HASH_LENGTH,
  INITIAL_POOL_SHARE_VALUE,
  INSURANCE_FUND_OPERATOR_ACCOUNT_INDEX,
  IOC_EXPIRY,
  L1_MESSAGE_TX_TYPES,
  L1_SIGNATURE_LENGTH,
  L1_SIG_TX_TYPES,
  L1_TEMPLATES,
  MARGIN_FRACTION_TICK,
  MAX_ACCOUNT_INDEX,
  MAX_API_KEY_INDEX,
  MAX_ASSET_INDEX,
  MAX_ASSET_MARGIN_MODE,
  MAX_ATTRIBUTE_TYPE,
  MAX_BURNT_SHARE_USDC_VALUE,
  MAX_CLIENT_ORDER_INDEX,
  MAX_EXCHANGE_USDC,
  MAX_GROUPED_ORDER_COUNT,
  MAX_INITIAL_TOTAL_SHARES,
  MAX_INITIAL_TOTAL_STAKING_SHARES,
  MAX_INVESTED_PUBLIC_POOL_COUNT,
  MAX_MASTER_ACCOUNT_INDEX,
  MAX_ORDER_BASE_AMOUNT,
  MAX_ORDER_CANCEL_ALL_PERIOD,
  MAX_ORDER_EXPIRY,
  MAX_ORDER_EXPIRY_PERIOD,
  MAX_ORDER_INDEX,
  MAX_ORDER_NONCE,
  MAX_ORDER_PRICE,
  MAX_ORDER_TRIGGER_PRICE,
  MAX_PERPS_MARKET_INDEX,
  MAX_POOL_ENTRY_USDC,
  MAX_POOL_SHARES,
  MAX_POOL_SHARES_TO_MINT_OR_BURN,
  MAX_SPOT_MARKET_INDEX,
  MAX_STAKING_POOL_SHARES,
  MAX_STAKING_SHARES_TO_MINT_OR_BURN,
  MAX_STRATEGY_INDEX,
  MAX_TIMESTAMP,
  MAX_TRANSFER_AMOUNT,
  MAX_WITHDRAWAL_AMOUNT,
  MEMO_LENGTH,
  MINT_SHARES_SCHEMA,
  MIN_ACCOUNT_INDEX,
  MIN_API_KEY_INDEX,
  MIN_ASSET_INDEX,
  MIN_CLIENT_ORDER_INDEX,
  MIN_INITIAL_TOTAL_SHARES,
  MIN_INITIAL_TOTAL_STAKING_SHARES,
  MIN_MARKET_INDEX,
  MIN_NONCE,
  MIN_ORDER_BASE_AMOUNT,
  MIN_ORDER_CANCEL_ALL_PERIOD,
  MIN_ORDER_EXPIRY,
  MIN_ORDER_EXPIRY_PERIOD,
  MIN_ORDER_INDEX,
  MIN_ORDER_NONCE,
  MIN_ORDER_PRICE,
  MIN_ORDER_TRIGGER_PRICE,
  MIN_PERPS_MARKET_INDEX,
  MIN_POOL_SHARES_TO_MINT_OR_BURN,
  MIN_SPOT_MARKET_INDEX,
  MIN_STAKING_SHARES_TO_MINT_OR_BURN,
  MIN_STRATEGY_INDEX,
  MIN_SUB_ACCOUNT_INDEX,
  MIN_TRANSFER_AMOUNT,
  MIN_WITHDRAWAL_AMOUNT,
  MODIFY_ORDER_SCHEMA,
  MarginDirection,
  MarginMode,
  NATIVE_ASSET_INDEX,
  NB_ATTRIBUTES_PER_TX,
  NIL_API_KEY_INDEX,
  NIL_ASSET_INDEX,
  NIL_CLIENT_ORDER_INDEX,
  NIL_INTEGRATOR_INDEX,
  NIL_INTEGRATOR_MAKER_FEE,
  NIL_INTEGRATOR_TAKER_FEE,
  NIL_MARKET_INDEX,
  NIL_ORDER_BASE_AMOUNT,
  NIL_ORDER_EXPIRY,
  NIL_ORDER_INDEX,
  NIL_ORDER_PRICE,
  NIL_ORDER_TRIGGER_PRICE,
  NIL_STRATEGY_INDEX,
  NO_CLIENT_ORDER_INDEX,
  ONE_LIT,
  ONE_USDC,
  ORDER_LEAF_ELEMENT_COUNT,
  ORDER_SCHEMAS,
  ORDER_SCHEMA_REGISTRY,
  OrderTimeInForce,
  OrderType,
  PRIVATE_KEY_LENGTH,
  PUBKEY_LENGTH,
  PoolStatus,
  SHARE_TICK,
  SIGNATURE_LENGTH,
  STAKE_ASSETS_SCHEMA,
  SelfTradeBehavior,
  SelfTradeEquality,
  TRANSFER_SCHEMA,
  TREASURY_ACCOUNT_INDEX,
  TX_SCHEMAS,
  TxType,
  UNSTAKE_ASSETS_SCHEMA,
  UPDATE_ACCOUNT_ASSET_CONFIG_SCHEMA,
  UPDATE_ACCOUNT_CONFIG_SCHEMA,
  UPDATE_LEVERAGE_SCHEMA,
  UPDATE_MARGIN_SCHEMA,
  UPDATE_PUBLIC_POOL_SCHEMA,
  USDC_ASSET_INDEX,
  WITHDRAW_SCHEMA,
  aggregateOrderHash,
  aggregateTxHash,
  airdropAllocationMessage,
  approveIntegratorMessage,
  attachL1Signature,
  attributeTypeSlots,
  attributesAreEmpty,
  attributesHash,
  attributesToJson,
  buildApproveIntegrator,
  buildBurnShares,
  buildCancelAllOrders,
  buildCancelOrder,
  buildChangePubKey,
  buildCreateGroupedOrders,
  buildCreateOrder,
  buildCreatePublicPool,
  buildCreateSubAccount,
  buildMintShares,
  buildModifyOrder,
  buildStakeAssets,
  buildTransfer,
  buildUnstakeAssets,
  buildUpdateAccountAssetConfig,
  buildUpdateAccountConfig,
  buildUpdateLeverage,
  buildUpdateMargin,
  buildUpdatePublicPool,
  buildWithdraw,
  changePubKeyMessage,
  createSubAccountMessage,
  createTxSchemaRegistry,
  defineTxSchema,
  eip191Message,
  expiryIn,
  groupedOrderElements,
  hashTx,
  hashTxHex,
  hex16,
  i16,
  i64,
  isHashable,
  l1MessageFor,
  marketKind,
  memoFromHex,
  memoFromUtf8,
  normalizeAttributes,
  orderInfoOf,
  orderLeafElements,
  orderLeafHash,
  ordersToJson,
  pubKeyToFieldElements,
  readTxField,
  requireTxSchema,
  requiresL1Signature,
  resolveOpts,
  schemaField,
  serializeTx,
  signTx,
  splitI64Arith,
  splitU64,
  toField,
  toTxInfo,
  transferMessage,
  txHash,
  txHashElements,
  txHashHex,
  txSubmission,
  u16,
  u32,
  u64,
  u8,
  validateApproveIntegrator,
  validateAttributes,
  validateBurnShares,
  validateCancelAllOrders,
  validateCancelOrder,
  validateChangePubKey,
  validateChildOrder,
  validateCreateGroupedOrders,
  validateCreateOrder,
  validateCreatePublicPool,
  validateCreateSubAccount,
  validateMintShares,
  validateModifyOrder,
  validateOrderCore,
  validateOrderTypeMatrix,
  validateParentOrder,
  validateSiblingPair,
  validateStakeAssets,
  validateTransfer,
  validateTriggerPriceRange,
  validateUnstakeAssets,
  validateUpdateAccountAssetConfig,
  validateUpdateAccountConfig,
  validateUpdateLeverage,
  validateUpdateMargin,
  validateUpdatePublicPool,
  validateWithdraw,
} from "./tx/index.js";
export type {
  AccountAssetMarginModeCode,
  AccountFamilyTx,
  AccountTradingModeCode,
  AccountValidateOptions,
  AirdropAllocationMessageArgs,
  ApproveIntegratorMessageArgs,
  ApproveIntegratorRequest,
  ApproveIntegratorTx,
  AssetMarginModeCode,
  AssetRouteTypeCode,
  AttributeSpec,
  AttributeType,
  BaseAccountTx,
  BurnSharesRequest,
  BurnSharesTx,
  CancelAllOrdersRequest,
  CancelAllOrdersTx,
  CancelAllTimeInForceCode,
  CancelOrderRequest,
  CancelOrderTx,
  ChainIdCode,
  ChainName,
  ChangePubKeyMessageArgs,
  ChangePubKeyRequest,
  ChangePubKeyTx,
  CreateGroupedOrdersRequest,
  CreateGroupedOrdersTx,
  CreateOrderRequest,
  CreateOrderTx,
  CreatePublicPoolRequest,
  CreatePublicPoolTx,
  CreateSubAccountMessageArgs,
  CreateSubAccountRequest,
  CreateSubAccountTx,
  Enc,
  EthPersonalSigner,
  FieldSpec,
  GroupingTypeCode,
  I16,
  I64,
  L1SigHex,
  L1TemplateName,
  MarginDirectionCode,
  MarginModeCode,
  MintSharesRequest,
  MintSharesTx,
  ModifyOrderRequest,
  ModifyOrderTx,
  OrderInfo,
  OrderTimeInForceCode,
  OrderTx,
  OrderTypeCode,
  OrderValidateOptions,
  PoolStatusCode,
  ResolvedTransactOpts,
  SelfTradeBehaviorCode,
  SelfTradeEqualityCode,
  SignedAccountFamilyTx,
  SignedTx,
  StakeAssetsRequest,
  StakeAssetsTx,
  TransactOpts,
  TransferMessageArgs,
  TransferRequest,
  TransferTx,
  TxAttributes,
  TxLike,
  TxSchema,
  TxSchemaRegistry,
  TxSubmission,
  TxTypeCode,
  TxTypeName,
  U16,
  U32,
  U64,
  U8,
  UnsignedTx,
  UnsignedTxLike,
  UnstakeAssetsRequest,
  UnstakeAssetsTx,
  UpdateAccountAssetConfigRequest,
  UpdateAccountAssetConfigTx,
  UpdateAccountConfigRequest,
  UpdateAccountConfigTx,
  UpdateLeverageRequest,
  UpdateLeverageTx,
  UpdateMarginRequest,
  UpdateMarginTx,
  UpdatePublicPoolRequest,
  UpdatePublicPoolTx,
  WithdrawRequest,
  WithdrawTx,
} from "./tx/index.js";

/* ------------------------------------------------------------------------------------------------ */
/* REST routes, transport, pagination — also `lighter-ts/rest` */
/* ------------------------------------------------------------------------------------------------ */
export {
  DEFAULT_MAX_PAGES,
  LighterGeoRestrictedError,
  LighterRestClient,
  REQUEST_ID_HEADER,
  buildQuery,
  buildUrl,
  classifyResponse,
  expandExponent,
  isLighterGeoRestrictedError,
  isRetryableStatus,
  isSuccess,
  mapCandle,
  mapCandles,
  nextCursor,
  paginate,
  paginateItems,
  parseRetryAfterMs,
  request,
  retryDelayMs,
  routes,
  stripTrailingSlash,
} from "./rest/index.js";
export type {
  CallOptions,
  Classification,
  GroupFacade,
  ItemOf,
  MappedCandle,
  PaginateOptions,
  ParamsOf,
  RawCallOptions,
  RequestOptions,
  ResponseFacts,
  ResponseOf,
  RestAuth,
  RestEncoding,
  RestGroup,
  RestMethod,
  RouteDef,
  RouteKey,
  RouteMethod,
  RouteTable,
} from "./rest/index.js";

/* ------------------------------------------------------------------------------------------------ */
/* WebSocket transport, subscriptions, protocol — also `lighter-ts/ws` */
/* ------------------------------------------------------------------------------------------------ */
export {
  ASSET_DECIMALS,
  AccountAssetsState,
  BackoffController,
  InflightSemaphore,
  LighterWsAuthError,
  LighterWsClient,
  LighterWsClosedError,
  LighterWsError,
  LighterWsOverflowError,
  LighterWsRateLimitError,
  LighterWsReadOnlyError,
  LighterWsTimeoutError,
  MAX_TX_BATCH_SIZE,
  TokenBucket,
  WS_ACK_CODE_MISSING,
  WS_ACK_CODE_OK,
  WS_ERR_ALREADY_SUBSCRIBED,
  WS_ERR_API_KEY_NOT_FOUND,
  WS_ERR_API_TOKEN_NOT_FOUND,
  WS_ERR_API_TOKEN_REVOKED,
  WS_ERR_FAILED_TO_CONNECT,
  WS_ERR_FAILED_TO_FETCH,
  WS_ERR_FAILED_TO_SUBSCRIBE,
  WS_ERR_INVALID_ACCOUNT_TYPE,
  WS_ERR_INVALID_API_KEY_INDEX,
  WS_ERR_INVALID_CHANNEL,
  WS_ERR_INVALID_DATA,
  WS_ERR_INVALID_JSON,
  WS_ERR_INVALID_SIGNATURE,
  WS_ERR_INVALID_TYPE,
  WS_ERR_NOT_SUBSCRIBED,
  WS_ERR_OPERATION_NOT_SUPPORTED,
  WS_ERR_TOO_MANY_ACCOUNTS,
  WS_ERR_TOO_MANY_CONNECTIONS,
  WS_ERR_TOO_MANY_INFLIGHT,
  WS_ERR_TOO_MANY_MESSAGES,
  WS_ERR_TOO_MANY_REQUESTS,
  WS_ERR_TOO_MANY_SUBSCRIPTIONS,
  WS_ERR_TOO_MANY_WITHDRAWALS,
  WsTransport,
  buildPong,
  buildSendTx,
  buildSendTxBatch,
  buildSubscribe,
  buildUnsubscribe,
  channels,
  classifyCloseCode,
  classifyWsError,
  createSubscription,
  createTxDispatcher,
  decodeAccountTxEventInfo,
  decodeAccountTxInfo,
  decodeFrame,
  diagnoseUpgradeFailure,
  familyFromType,
  isDeleverageNotification,
  isLighterWsError,
  isLiquidationNotification,
  normaliseChannelKey,
  resolveRouteKey,
  upgradeProbeUrl,
  wireInt,
  wsLimitName,
} from "./ws/index.js";
export type {
  AccountAllMessage,
  AccountAllOrdersMessage,
  AccountAllPositionsMessage,
  AccountAllTradesSnapshot,
  AccountAllTradesUpdate,
  AccountAssetsMessage,
  AccountMarketMessage,
  AccountOrdersMessage,
  AccountTx,
  AccountTxEventInfo,
  AccountTxInfo,
  AccountTxMessage,
  AssetBalance,
  AuthTokenProvider,
  BackoffOptions,
  CandleMessage,
  CandleResolution,
  ChannelEvent,
  ChannelName,
  ChannelSpec,
  CloseClass,
  CloseClassification,
  CloseContext,
  DeleverageContent,
  DeleverageNotification,
  HeightMessage,
  InboundFrame,
  InflightTicket,
  LighterWsClosedErrorOptions,
  LighterWsErrorOptions,
  LighterWsOptions,
  LighterWsOverflowErrorOptions,
  LighterWsRateLimitErrorOptions,
  LighterWsTimeoutErrorOptions,
  LiquidationContent,
  LiquidationNotification,
  MarkPriceCandle,
  MarkPriceCandleMessage,
  MarketStats,
  MarketStatsMessage,
  Notification,
  NotificationCommon,
  NotificationMessage,
  OrderBookLevel,
  OrderBookMessage,
  OrderBookPayload,
  OverflowPolicy,
  PoolDailyReturn,
  PoolDataMessage,
  PoolInfo,
  PoolInfoMessage,
  PoolShare,
  PoolSharePrice,
  PoolStrategy,
  Position,
  Rfq,
  RfqMessage,
  RouteResult,
  SendTxAck,
  SendTxBatchAck,
  SendTxBatchFrameInput,
  SendTxBatchOptions,
  SendTxFrameInput,
  SendTxOptions,
  SpotAvgEntry,
  SpotAvgEntryMessage,
  SpotMarketStats,
  SpotMarketStatsMessage,
  SubscribeOptions,
  Subscription,
  SubscriptionController,
  SubscriptionDiagnostic,
  SubscriptionHost,
  TickerMessage,
  TickerPayload,
  TokenBucketOptions,
  TradeMessage,
  TxDispatcher,
  TxDispatcherOptions,
  UnknownNotification,
  UpgradeDiagnosis,
  UserStats,
  UserStatsFigures,
  UserStatsMessage,
  WireInt,
  WsChannelEnvelope,
  WsClientDiagnostic,
  WsClientState,
  WsDiagnostic,
  WsErrorAction,
  WsErrorContext,
  WsErrorTag,
  WsFrameChannel,
  WsSendLane,
  WsSendOptions,
  WsState,
  WsSubscriber,
  WsTransportOptions,
} from "./ws/index.js";

/* ------------------------------------------------------------------------------------------------ */
/* The stateful trading client — also `lighter-ts/client` */
/* ------------------------------------------------------------------------------------------------ */
export {
  AssetRegistry,
  DEFAULT_AUTH_TOKEN_EXPIRY_SECONDS,
  DEFAULT_BOOK_DEPTH,
  DEFAULT_ORDER_EXPIRY_MS,
  LighterAccount,
  LighterClient,
  MAX_AUTH_TOKEN_LIFETIME_SECONDS,
  MarketHandle,
  MarketRegistry,
  NO_ORDER_INTEGERS,
  PENDING_NONCE,
  PERPS_MARKET_INDEX_RANGE,
  READ_ONLY_API_KEY_INDEX,
  SPOT_MARKET_INDEX_RANGE,
  SystemConfigCache,
  TOP_OF_BOOK_DEPTH,
  areKeysEqual,
  assertGroupLegality,
  batch,
  bestPrice,
  bookFromLevels,
  bookFromRestOrders,
  buildOco,
  buildOto,
  buildOtoco,
  createApiKey,
  createAuthToken,
  createNonceSource,
  generateAuthTokenSchedule,
  leverageToImf,
  lookupToken,
  marketHandle,
  normalizeTxHash,
  parseSlippage,
  potentialExecutionPrice,
  quoteToBase,
  restBookSource,
  sequence,
  slippageBound,
  txHashesEqual,
} from "./client/index.js";
export type {
  AccountContext,
  AccountOptions,
  Applied,
  AppliedReceipt,
  AssetInfo,
  AssetSnapshot,
  AuthTokenContext,
  AuthTokenSchedule,
  AuthTokenScheduleOptions,
  BaseSizing,
  BatchContext,
  BatchOptions,
  BookLevel,
  BookSnapshot,
  BookSource,
  BracketOpts,
  CancelAllOpts,
  CreateAuthTokenOptions,
  Decimals,
  Duration,
  EntryOpts,
  ExecutionEstimate,
  Fraction,
  GeneratedApiKey,
  GroupPlan,
  IntegratorConfig,
  LeverageApplied,
  LeverageInput,
  LeverageOpts,
  LeverageResult,
  LighterClientOptions,
  LimitOpts,
  LoadOptions,
  MarginModeName,
  MarketConfigInfo,
  MarketContext,
  MarketFilter,
  MarketInfo,
  MarketLookup,
  MarketQuery,
  MarketSnapshot,
  ModifyOpts,
  NonceKeySnapshot,
  NonceLease,
  NonceOutcome,
  NonceSnapshot,
  NonceSource,
  NonceSourceKind,
  NonceSourceOptions,
  OrderBookTransport,
  OtoOpts,
  PerpsMarketInfo,
  PositionBracketOpts,
  PrepareOpts,
  PriceRounding,
  QuoteSizing,
  RawTxOpts,
  RawTxSurface,
  RegistryOptions,
  SendOpts,
  SequenceContext,
  SequenceOptions,
  SequencePrepareOpts,
  SequenceSendOpts,
  SizedOrderOpts,
  SizingOptions,
  SlippageMode,
  SubmitChannel,
  SubmitContext,
  SubmitTransport,
  SystemConfigInfo,
  TimeInForceName,
  TradeCallOptions,
  TradingAccount,
  TriggerFamily,
  TriggerOpts,
  TxReceipt,
  TxResult,
  WaitOptions,
} from "./client/index.js";

/* ------------------------------------------------------------------------------------------------ */
/* Package identity */
/* ------------------------------------------------------------------------------------------------ */
export {
  NAME,
  VERSION,
} from "./version.js";

/* ------------------------------------------------------------------------------------------------ */
/* Wire models. No subpath of their own — see the header. Types only, all erased. */
/* ------------------------------------------------------------------------------------------------ */

// account
export {
  signedPositionSize,
} from "./models/account.js";
export type {
  Account,
  AccountApiKeys,
  AccountAsset,
  AccountLimits,
  AccountMetadata,
  AccountMetadataObject,
  AccountMetadatas,
  AccountPosition,
  ApprovedIntegrator,
  DetailedAccount,
  DetailedAccounts,
  LiqTrade,
  Liquidation,
  LiquidationInfo,
  LiquidationInfos,
  PendingUnlock,
  PoolSeriesEntry,
  PositionFunding,
  PositionFundings,
  PublicPoolInfo,
  PublicPoolShare,
  ReqChangeAccountTier,
  ReqPostApiToken,
  ReqRevokeApiToken,
  ReqSetAccountMetadata,
  ReqSetMakerOnlyApiKeys,
  RiskInfo,
  RiskParameters,
  SubAccounts,
} from "./models/account.js";

// common
export type {
  CursorPage,
  Cursored,
  DecimalString,
  EpochMicros,
  EpochMs,
  EpochSeconds,
  Int64String,
  LegacyCursored,
  MarketKind,
  MarketStatus,
  MarketType,
  PositionSide,
  ResultCode,
  Role,
  Side,
  SortDir,
  UnmodelledResponse,
} from "./models/common.js";

// lease
export type {
  LeaseEntry,
  LeaseOptionEntry,
  LeaseStatus,
  ReqLITLease,
  RespGetLeaseOptions,
  RespGetLeases,
} from "./models/lease.js";

// market
export type {
  Asset,
  AssetDetails,
  Funding,
  FundingRate,
  FundingRates,
  Fundings,
  MarketConfig,
  OrderBook,
  OrderBookDetails,
  OrderBooks,
  PerpsOrderBookDetail,
  SpotOrderBookDetail,
  SystemConfig,
} from "./models/market.js";

// misc
export type {
  AccountPnL,
  Announcement,
  Announcements,
  ApiToken,
  BridgeSupportedNetwork,
  BridgeSupportedNetworks,
  ContractAddress,
  CreateIntentAddressResp,
  Deposit,
  DepositHistory,
  DepositHistoryItem,
  DepositStatus,
  ExchangeMetric,
  ExchangeStats,
  ExecuteStat,
  ExportData,
  L1ProviderInfo,
  Layer1BasicInfo,
  OrderBookStats,
  PnLEntry,
  ReqAckNotif,
  ReqCreateIntentAddress,
  ReqFastwithdraw,
  RespChangeAccountTier,
  RespGetApiTokens,
  RespGetExchangeMetrics,
  RespGetExecuteStats,
  RespGetFastBridgeInfo,
  RespGetFastwithdrawalInfo,
  RespGetMakerOnlyApiKeys,
  RespPostApiToken,
  RespRevokeApiToken,
  RespSetMakerOnlyApiKeys,
  RespSyntheticSpotInfo,
  RespWithdrawalDelay,
  SlippageResult,
  Status,
  Token,
  TokenList,
  TransferFeeInfo,
  TransferHistory,
  TransferHistoryItem,
  TransferKind,
  ValidatorInfo,
  WithdrawHistory,
  WithdrawHistoryItem,
  WithdrawStatus,
  ZkLighterInfo,
} from "./models/misc.js";

// order
export type {
  Candle,
  Candles,
  Order,
  OrderBookOrders,
  OrderStatus,
  Orders,
  SimpleOrder,
  TimeInForce,
  Trade,
  TradeType,
  Trades,
  TriggerStatus,
} from "./models/order.js";

// pool
export type {
  DailyReturn,
  PublicPoolInfoDetail,
  PublicPoolMetadata,
  RespPublicPoolsMetadata,
  SharePrice,
  Strategy,
} from "./models/pool.js";

// referral
export type {
  L1Metadata,
  PartnerStats,
  Referral,
  ReferralCode,
  ReferralPointEntry,
  ReferralPoints,
  ReqCreateReferralCode,
  ReqUpdateKickback,
  ReqUpdateReferralCode,
  ReqUseReferralCode,
  RespUpdateKickback,
  RespUpdateReferralCode,
  TradeStats,
  UserReferrals,
} from "./models/referral.js";

// rfq
export type {
  RFQEntry,
  RFQListStatus,
  RFQMetadata,
  RFQResponseEntry,
  RFQResponseStatus,
  RFQUpdateStatus,
  ReqCreateRFQ,
  ReqRespondToRFQ,
  ReqUpdateRFQ,
  RespCreateRFQ,
  RespGetRFQ,
  RespListRFQs,
  RespRFQ,
  RespRespondToRFQ,
  RespUpdateRFQ,
} from "./models/rfq.js";

// transaction
export type {
  Block,
  Blocks,
  CurrentHeight,
  EnrichedTx,
  NextNonce,
  ReqSendTx,
  ReqSendTxBatch,
  RespSendTx,
  RespSendTxBatch,
  Tx,
  TxHash,
  Txs,
} from "./models/transaction.js";
